version: '3'

services:
  # db:
  #   image: postgres
  #   volumes:
  #     - influencer_api:/var/lib/postgresql/data/
  #   env_file:
  #     - ./services/database/.env
  #   ports:
  #     - 5432:5432

  redis:
    image: redis
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - redis:/data

  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - type: volume
        source: es_data
        target: /usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - search-service

  kibana:
    image: kibana:8.6.2
    ports:
      - target: 5601
        published: 5601
    networks:
      - search-service
    depends_on:
      - elasticsearch  

networks:
  search-service:
    name: search-service
    driver: bridge

volumes:
  quotes_scraper:
  es_data:
  redis:
    driver: local